version: "3.9"

services:
  homeassistant:
    image: ghcr.io/gittiralf/homeassistant-custom:latest
    container_name: homeassistant-custom
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
